### ISSUE TITLE
Ex-Yu države 

### ISSUE THREAD

**Issue by xs1vr** [trbsi/YugoCar#1]
Aplikacija trenutno radi samo za HR a BlaBla smo koristili i mi vani (čitaj Srbija, BiH, CG)

Ako se autor slaže da uradimo ovo?

**Comment by trbsi** [comment]
Uh sorry nisam dobio notifikaciju za ovo, a radio sam na mob applikaciji ovih dana pa sam bio zauzet.

Naravno da se slažem. Samo treba prevest (nema puno za prevest) i trebam popis gradova. Ovo je primjer jsona https://github.com/trbsi/YugoAuto/blob/master/database/seeders/data/places.json
Bitno da ima "city" samo to čitam. A iz imena fajla ću znati koja je država

**Comment by trbsi** [comment]
@tk2p  ping za ovo

**Comment by wast** [comment]
Upitao ChatGPT da generira listu gradova pa evo PR :)
