### ISSUE TITLE
Filter color issue

### ISSUE THREAD

**Issue by skurdija** [trbsi/YugoCar#2]
Hey,

When I was checking your site I noticed problems with the filter colors, as shown in the screenshot:
![Screenshot 2023-04-07 at 09 16 14](https://user-images.githubusercontent.com/3019333/230561731-ce19eb52-2cd6-4819-8a77-fdbe27780733.png)

I guess the background should be grey same as other fields.

**Comment by trbsi** [comment]
Nice catch. I will fix it today

**Comment by trbsi** [comment]
Resolved and deployed. It should be ok now. If not, just reopen this
