### ISSUE TITLE
Neka vrsta verifikacije

### ISSUE THREAD

**Issue by MrCrobben** [trbsi/YugoCar#3]
Buduci da ima jako puno prevaranta i nije bas svatko entuzijastican sjesti bilo kome u auto i vice versa neka verifikacija bi trebala biti zbog zastite korisnika. Na zalost PHP mi nije jaca strana tako da ne mogu doprinjeti projektu iako bih volio :/

**Comment by trbsi** [comment]
Neka sugestija u vezi verifikacije? I o kakvoj bi se verifikaciji radilo?

**Comment by MrCrobben** [comment]
Stavio bih kao obavezno slika gdje se jasno vidi lice osobe, adresu (sto ne znam da bi bas svatko htio dati ali bi se samo spremalo na serveru nikako davalo na uvid korisnicima...) i povezivanje drustvene mreze.

Nadodao u aplikaciju panic button i naveo da djele svoju lokaciju prije voznje nekom prijatelju preko whatsappa

**Comment by trbsi** [comment]
- Sto se tice povezivanja s drustvenom mrezom, Facebook koliko toliko nudi neku autenticnost no da bi se koristion FB Login, Facebook trazi verificiranje biznisa, sto ja u ovom trenutku nemam
- Obavezna slika mi je ok, ali tu ne mogu potvrditi da je na slici covjek koji se predstavlja da je
- Sto se tice adrese, tu ne znam sto da velim jer koja bi svrha bila da korisnik da svoju osobnu adresu?
- Za panic button, to se moze dati samo kao prijedlog

**Comment by vedranb7** [comment]
Nažalost, koliko god meni puta prosla takva misao i za BlaBlaCar (ili moje idejne alternative tome), ja isto sumnjam da bi verifikacija mogla proći na takav način ni da bi ju korisnici samo tako prihvatili, a i GDPR je upitan. Fotografija možda može pomoći, no također je istu vrlo lako skinuti s interneta.. mozda bi nekakva opcija bila (ako već nije) da korisnik obvezno mora upisati registracijske tablice vozila i koje vozilo je u pitanju. Na taj način osobe koje rezerviraju vožnju mogu proslijediti taj info sebi bitnim ljudima, just in case. Te naravno, feedback sustav gdje vozaci dobiju kritiku od suvozača nakon vožnje.

**Comment by CarSig** [comment]
znam da je aplikacija besplatna , ali za verifikaciju bi se mogli koristiti podatci s kreditne kartice

**Comment by trbsi** [comment]
> Verifikacija putem kartice...

Onda postajem BlaBlaCar :D samo moram počet naplaćivati

> Verifikacija registracijski tablica

To je dobro no netko može staviti bilo čije i reći: e auto mi je na popravku ili što god pa sam uzeo očev auto ovaj put

Može se verificirati osobnom. Ima način za verifikaciju, problem je što ja te podatke ne smijem (niti želim) čuvati zbog GDPRa. Pogotovo neke super osobne podatke ili čak slike tipa slika osobne. Čak i da se korisnik verificira tipa "Josip Horvat" kojih ima onak na tisuće, i da bude nešto ja i dalje nemam nikakve podatke o njemu, ne znam koji Josip Horvat jer ne čuvam nikakve osobne podatke zbog GDPRa

Moram jako dobro razmisliti da to ima smisla, da ljudima ne bude tlaka to napraviti i da bude u skladu sa GDPR i s čim već mora biti
