### ISSUE TITLE
GitHub link ne radi u Android appu

### ISSUE THREAD

**Issue by wast** [trbsi/YugoCar#6]
Možda treba stavit about:blank umjesto _blank

**Comment by trbsi** [comment]
Da. Mislim da cu to morati namjestiti direkt unutar app-a. Ostavljam ovaj issue otvorenim dok mi trenutna verzija ne bude odobrena jer tamo imam bitniji fix

Rjesenje: https://stackoverflow.com/questions/65292270/flutter-webview-opening-external-links-in-browser-or-window

**Comment by trbsi** [comment]
Fixano u novoj verziji. Nova verzija je live
