### ISSUE TITLE
Session persistence ne radi u Android app

### ISSUE THREAD

**Issue by wast** [trbsi/YugoCar#7]
Nakon ponovnog otvaranja appa više nisam ulogiran.

**Comment by trbsi** [comment]
Kad ubijes aplikaciju ili kad normalno udes? Jer ja sam bas instalirao app, logirao se sa "remember me" i drži me logiranim

**Comment by wast** [comment]
Ubijem ju iz backgrounda, ponovno uđem i nisam ulogiran. Huawei P30 Pro.

**Comment by trbsi** [comment]
Auf, nisam racunao na ubijanje aplikacije a vjerujem da ljudi to znaju raditi. Moram dobro razmisliti kako to rijesiti

**Comment by trbsi** [comment]
Al evo ja na iPhoneu 13 i na Samsung Galaxy A50 ubijem app i vratim se i logiran sam.
Jesi se logirao sa "remember me" opcijom?

**Comment by wast** [comment]
Da. Sa Remember me.
Evo probao sam restart mobitela i onda ostanem ulogiran. Ali kad ubijem app, onda više nisam 🤔

**Comment by trbsi** [comment]
Ajd probaj obrisat app, instalirat sa store opet pa vidjet hoce li opet. Ako ne radi opet onda jedino sto mozemo na meet pa da vidimo jer ne mogu uopce reproducirat na 2 moba

**Comment by wast** [comment]
Nakon reinstall više ne mogu reproducirat 😄

**Comment by trbsi** [comment]
hahaha mozda je zbog verzije, updateao sam verziju pa mozda je tu bilo nekih izmjena. Zatvorit cu issue, pa ako bas bude opet otvori ga :D
