### ISSUE TITLE
Filter is broken

### ISSUE THREAD

**Issue by nikola-lenert** [trbsi/YugoCar#9]
![image](https://github.com/trbsi/YugoAuto/assets/66955219/01a25ac1-c57f-4fa0-9bc6-7919a320bdfb)

Steps to reproduce:
1. Be logged out
2. Starting point: Dubrovnik
3. Destination: Zagreb
4. Search
5. Get result from image above

**Comment by trbsi** [comment]
Evo ga, sada je popravljeno. Hvala

**Comment by trbsi** [comment]
P.S. Ako treba slobodno otvori issue opet
